### ISSUE TITLE
[Request]: XML loader

### ISSUE THREAD

**Issue by TheGreenBandit** [howdoiusekeyboard/SechsMenu#27]
### Problem

I'd love to see an xml loader in the menu as it would be a fun additon, maybe an asi loader too???

### Solution

XML loader added to menu

### Reason

Would be fun

### Additional context

with an xml loader u can attach random shit like windmills to cars, pretty fun

**Comment by boredom1234** [comment]
Ok, Will Check it out!

**Comment by TheGreenBandit** [comment]
?

**Comment by boredom1234** [comment]
Upstream has been added with a .json loader, Some presets will be shared :)
