### ISSUE TITLE
Rockstar Id Joiner

### ISSUE THREAD

**Issue by TheGreenBandit** [howdoiusekeyboard/SechsMenu#28]
### Problem

A rockstar id joiner so if someone else is using the menu and spoofing their name you can join them without them having to stop spoofing

### Solution

rockstar id joiner added

### Reason

would help you to join friends

### Additional context

idk

**Comment by boredom1234** [comment]
(added) __Don't be TOXIC,  or you will be spanked.

**Comment by TheGreenBandit** [comment]
lmao thanks man, love the menu

**Comment by TheGreenBandit** [comment]
question tho, how come u need to have them added in a crew and not just on your friends list?

**Comment by boredom1234** [comment]
Wdym?

**Comment by fellicienne** [comment]
@boredom1234 My gta is constantly crashing after this commit

**Comment by TheGreenBandit** [comment]
same for me, its in online btw

**Comment by boredom1234** [comment]
Wait for a fix.

**Comment by howdoiusekeyboard** [comment]
ETA: Probably aftergame updates.

**Comment by TheGreenBandit** [comment]
rockstar joiner drafts in this (https://github.com/YimMenu/YimMenu/issues/172)

**Comment by howdoiusekeyboard** [comment]
Closing this since its worked on from upstream
